### ISSUE TITLE
Allow to use whitespaces for Samba printers

### ISSUE THREAD

**Issue by r3d9u11** [zdohnal/system-config-printer#113]
Hi. Is it possible to add support a whitespaces for name of samba printer?
Now users must to write code of whitespaces (%20) instead of symbols (if they know about this trick)
![screenshot at 2018-08-10 10-17-00](https://user-images.githubusercontent.com/15020827/43944281-1081efe8-9c87-11e8-8a26-c1b10864d034.png)
Thanks.

**Comment by zdohnal** [comment]
Hi,
I think you are talking about device uri, not name. And what can be in device uri is defined by what actual backend (in this case smb backend) and CUPS expects to be in device URI. And what backend expects in URI is usually defined in a document/standard.
system-config-printer as GUI over (mostly) CUPS is copying syntax of CUPS and backends, so if you would like to allow whitespaces, so there is the place to ask.
I guess s-c-p could do some 'underground' changes, which will substitute whitespaces for %20, but it can create confusions during debugging - like user is seeing different URI in s-c-p than CUPS/backends actually uses.
With this reasoning, I'm closing the issue.
