### ISSUE TITLE
NameError when libsecret GIR bindings are not installed

### ISSUE THREAD

**Issue by jnumm** [zdohnal/system-config-printer#115]
Hello,

I'm trying the latest git revision on Debian 9.5. I configured with --prefix=$HOME/system-config-printer, ran make install, then tried to launch the application.

```
Traceback (most recent call last):
  File "/home/juhani/system-config-printer/share/system-config-printer/system-config-printer.py", line 84, in <module>
    import jobviewer
  File "/home/juhani/system-config-printer/share/system-config-printer/jobviewer.py", line 76, in <module>
    NETWORK_PASSWORD = Secret.Schema.new("org.system.config.printer.store", Secret.SchemaFlags.NONE,
NameError: name 'Secret' is not defined
```

This error goes away when I install the Debian package `gir1.2-secret-1`. it looks like jobviewer.py uses the name `Secret` even when gi.repository could not provide it.

If libsecret is not meant to be optional, then the import inside try in [jobviewer.py:56](https://github.com/zdohnal/system-config-printer/blob/master/jobviewer.py#L56) is misleading. On the other hand, if libsecret indeed is optional, `Secret` should not be used without checking the variable USE_SECRET.

**Comment by zdohnal** [comment]
Hi Juhani,
thank you for reporting this issue! The latest commit 42d95b7 should take care of it - the previous module used there - libgnome-keyring - was optional too, so it should stay optional.
