### ISSUE TITLE
Please add a `Quit-Button`

### ISSUE THREAD

**Issue by saitam1** [zdohnal/system-config-printer#119]
It is not possible to close the running program

**Comment by zdohnal** [comment]
There is 'Close' button in main view and in print applet window too. If you think otherwise, please attach screenshot.

**Comment by saitam1** [comment]
This was preinstalled on Ubuntu 18.04. or maybe 16.04., because I upgraded recently. How can I check which version this is?

![screenshot from 2018-08-31 12-53-46](https://user-images.githubusercontent.com/23245678/44908765-09826f00-ad1d-11e8-8ca1-00023b7bdf6e.png)

**Comment by zdohnal** [comment]
Do you have system-config-printer from Ubuntu repos? And what desktop environment do you use (gnome, KDE etc.)?
This icon should be visible only when there is a print job in queue and it shouldn't be visible at several wide used desktop as Gnome, KDE, Cinnamon.
And if you have Ubuntu packaged system-config-printer, then you should reach Ubuntu support first. They can do something different than upstream project has.

**Comment by saitam1** [comment]
Yes I have system-config-printer 1.5.11, there were some jobs in the queue, that's why  the icon was visible. I use Unity on Ubuntu 18.04
