### ISSUE TITLE
[Patch] Add GenericName

### ISSUE THREAD

**Issue by glixx** [zdohnal/system-config-printer#20]
``` diff
diff -ur system-config-printer.orig/po/system-config-printer.pot system-config-printer/po/system-config-printer.pot
--- system-config-printer.orig/po/system-config-printer.pot 2015-08-29 11:46:13.000000000 +0300
+++ system-config-printer/po/system-config-printer.pot  2015-08-29 11:53:27.000000000 +0300
@@ -2720,6 +2720,10 @@
 msgid "Configure printers"
 msgstr ""

+#: ../system-config-printer.desktop.in.h:3
+msgid "Graphical interface to configure the printing system"
+msgstr ""
+
 #: ../statereason.py:109
 msgid "Toner low"
 msgstr ""
diff -ur system-config-printer.orig/system-config-printer.desktop.in system-config-printer/system-config-printer.desktop.in
--- system-config-printer.orig/system-config-printer.desktop.in 2015-08-29 11:46:13.000000000 +0300
+++ system-config-printer/system-config-printer.desktop.in  2015-08-29 11:50:44.000000000 +0300
@@ -1,6 +1,7 @@
 [Desktop Entry]
 _Name=Print Settings
-_Comment=Configure printers
+_GenericName=Configure printers
+_Comment=Graphical interface to configure the printing system
 Exec=system-config-printer
 Terminal=false
 Type=Application
```

**Comment by twaugh** [comment]
Thanks.

The usual way of doing this is that you fork the repository (button at the top right), make your changes locally, push them back to GitHub in your forked repository, and submit a pull request.
https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project

In this particular case, I think the wording for the keys is wrong. The way I read the spec, and all the examples I've seen elsewhere, have `GenericName` as a noun phrase (e.g. 'web browser') and `Comment` as a verb phrase (e.g. 'browse the web').

**Comment by glixx** [comment]
You understood specification wrong.
GenericName is tooltip for Classic Menu KDE and menu item for Modern Menu KDE.

Total rule:
Name(short)<>GenericName(short enough)<>Comment(short or long)<>X-GNOME-FullName(short or long)

**Comment by twaugh** [comment]
But all the other examples I see use a noun phrase for the `GenericName` and a verb phrase for the `Comment`, including the actual specification.

Are they all wrong?

**Comment by glixx** [comment]
It is simple coincidence. Look at KDE apps.
GenericName is any string, but short enough to be placed as menu item. GenericName must not be the same with Name, Comment, etc.
Good to add X-GNOME-FullName also for GNOME apps.

**Comment by twaugh** [comment]
I've looked at the GNOME apps -- and system-config-printer is a GTK+ application, not one that will be used in KDE -- and *all* of them use it the way I described.

So I would much rather be consistent with both existing practice and the specification, and use noun/verb phrases.

I also do not want to have "Graphical interface to" in there. It's redundant.

Please re-submit as a pull request.

**Comment by glixx** [comment]
If you don't like my patch, then please write GenericName and X-GNOME-FullName what you like.

**Comment by zdohnal** [comment]
https://github.com/zdohnal/system-config-printer/commit/edb2eb6cd0f0e540f2ce0bf3d74bf1694d71373e solved.
