### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by bjornfor** [zdohnal/system-config-printer#44]
I was upgrading system-config-printer in NixOS to latest (1.5.7) and got these warnings:

```
$ system-config-printer
/nix/store/927mwjgzq9ak8wwsibgkf801axw08k3l-system-config-printer-1.5.7/share/system-config-printer/system-config-printer.py:32: PyGIWarning: Polkit was imported without specifying a version first. Use gi.require_version('Polkit', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Polkit
/nix/store/927mwjgzq9ak8wwsibgkf801axw08k3l-system-config-printer-1.5.7/share/system-config-printer/system-config-printer.py:36: PyGIWarning: GdkPixbuf was imported without specifying a version first. Use gi.require_version('GdkPixbuf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GdkPixbuf
/nix/store/927mwjgzq9ak8wwsibgkf801axw08k3l-system-config-printer-1.5.7/share/system-config-printer/system-config-printer.py:38: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gdk
/nix/store/927mwjgzq9ak8wwsibgkf801axw08k3l-system-config-printer-1.5.7/share/system-config-printer/system-config-printer.py:39: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/nix/store/927mwjgzq9ak8wwsibgkf801axw08k3l-system-config-printer-1.5.7/share/system-config-printer/jobviewer.py:28: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
```

I see this is fixed in master branch for almost a year. I noticed Ubuntu 16.04 doesn't have these warnings, although they also use 1.5.7. So either they use a post 1.5.7 snapshot (their source archive is named `system-config-printer_1.5.7+20160212.orig.tar.gz`) or they patch it themself.

Please make a new release as a synchronization point for downstreams, so we don't have to patch too (it takes time and feels like responsibility is inverted).

**Comment by prescott66** [comment]
+1 for new release, because of translation updates from Zanata.
Thank you.

**Comment by bigon** [comment]
I would be happy to see that happen too.

FYI (and if you care) the freeze for the next debian release (stretch) will start "soon", I would be happy to package a newer version of s-c-p before this happen

**Comment by zdohnal** [comment]
I made release 1.5.9. Previous version has the newest zanata translations.

**Comment by bigon** [comment]
Would it be possible to have the tarballs uploaded at their old location (http://cyberelk.net/tim/data/system-config-printer/)?

Or the plan is use the one autogenerated by github?

**Comment by zdohnal** [comment]
I uploaded tarball created by 'make dist', you can download it by link - https://github.com/zdohnal/system-config-printer/releases/download/v1.5.9/system-config-printer-1.5.9.tar.gz - maybe in future I will upload on cyberelk, but not now.
