### ISSUE TITLE
Program name not properly set

### ISSUE THREAD

**Issue by bigon** [zdohnal/system-config-printer#53]
Hi,

When starting system-config-printer the icon and the name of the application in the top bar of gnome-shell is not properly set.

Adding the following line to `system-config-printer.py` seems to fix the problem:

    GLib.set_prgname("system-config-printer")

`system-config-printer` here is the name of the .desktop file without the extension

**Comment by bigon** [comment]
There are other places that are also missing this I think, like `scp-dbus-service.py` and maybe other

**Comment by zdohnal** [comment]
Hi,
thank you for reporting issue and I'm sorry for late response - I'll add it to system-config-printer.py for now, if the issue will appear with other file, I'll add it there too.
Fixed as https://github.com/zdohnal/system-config-printer/commit/cc3650c765d0e31505d2f44fee697f385c14f14d for now.
