### ISSUE TITLE
dbus/org.fedoraproject.Config.Printing.service not regenerated during the build

### ISSUE THREAD

**Issue by bigon** [zdohnal/system-config-printer#54]
Hi,

This is related to the bug #28, It seems that the dbus/org.fedoraproject.Config.Printing.service is not removed during the clean meaning that the file included in the tarball is never regenerated and ends up with the /usr/local prefix

**Comment by zdohnal** [comment]
Hi,
thank you for reporting it, commit https://github.com/zdohnal/system-config-printer/commit/8c0450c877ad5bdfb992afc0a79b7178f66c6486 should fix it.
