### ISSUE TITLE
"Add" button when "There are no printers configured yet" is not properly aligned

### ISSUE THREAD

**Issue by whussiaefla** [zdohnal/system-config-printer#70]
When there are no printers configured yet, the "Add" button is aligned to the left, rather than centered like the message about no printers configured yet:

![add-button-left-aligned](https://user-images.githubusercontent.com/30831907/29070857-fa7eb49a-7c0e-11e7-9c1f-a348afe3eac4.png)

version 1.5.9

**Comment by zdohnal** [comment]
Fixed in current master.
