### ISSUE TITLE
"Print" messed up manual duplex printing  

### ISSUE THREAD

**Issue by gloschtla** [zdohnal/system-config-printer#71]
I am using Samsung SCX-3400 Series in Linux Mint 18.
This printer cannot turn papers to print on both sides, so I often did this manually and it was successful.

But this time the page numbers got messed up. I made these settings:
print pages 14-48
print odd pages (so it should print 15, 17, 19 ,.., 47)

result: it printed the page numbered 14, 16, .., 48

**Comment by zdohnal** [comment]
Hi,

system-config-printer is tool for printer configuration, this seems like CUPS issue. Please report your issue to CUPS project.

**Comment by gloschtla** [comment]
Thank you. I reposted it there: https://github.com/apple/cups/issues/5094
