### ISSUE TITLE
How can I save printer configurations

### ISSUE THREAD

**Issue by castagnag** [zdohnal/system-config-printer#75]
Hi, sorry it is not an issue but a request for help.

When I migrate a machine or reinstall fedora from scratch I would like to copy printer configurations to the new installation. Where does system-config-printer save the configuration files, please? Up to now I have to reinstall all the printers (there are many of them) from scratch every time.

Thank you in advance

Giuseppe

**Comment by zdohnal** [comment]
Hi,
system-config-printer is GUI for cups, so configuration for printers should be in /etc/cups directory, but I really recommend to install them again (especially HP printers, which needs proprietary plugin).

**Comment by castagnag** [comment]
Thanks a lot ... yes, I have mostly HP printers
