### ISSUE TITLE
Spanish config-printer Update

### ISSUE THREAD

**Issue by cyphra** [zdohnal/system-config-printer#78]
[system-config-printer.es.po.gz](https://github.com/zdohnal/system-config-printer/files/1507379/system-config-printer.es.po.gz)

**Comment by prescott66** [comment]
Translations are managed here: https://fedora.zanata.org/iteration/view/system-config-printer/master

**Comment by zdohnal** [comment]
@cyphra Hi,
thank you for the file - would you mind submitting it as merge request?

**Comment by prescott66** [comment]
Yes i can

**Comment by zdohnal** [comment]
@cyphra , please create a pull request.
