### ISSUE TITLE
Zanata update

### ISSUE THREAD

**Issue by prescott66** [zdohnal/system-config-printer#86]
Hi. Just wondering, if strings related changes are merged with Zanata translations.

**Comment by zdohnal** [comment]
Hi,
I wanted to do it when I release new version (in next year in January I think). There isn't any automatic way to do it right now, but feel free to add translations there.

**Comment by prescott66** [comment]
So i can update translation directly into the code via pull request? If POT is up to date...

**Comment by zdohnal** [comment]
Yes, and if you have access to Zanata, please update it there too.

**Comment by prescott66** [comment]
Many of new strings is hard to translate, becasuse of missing context....if is string related to print quality, paper, color mode etc... I.e. string "Color".

**Comment by zdohnal** [comment]
String related changes were merged to Zanata.
