### ISSUE TITLE
Add provides to appstream metadata

### ISSUE THREAD

**Issue by jbicha** [zdohnal/system-config-printer#99]
I was browsing the commit log and noticed you changed the id for your appstream metadata. Please add a provides id tag for the old name.

Here's an example:
https://gitlab.gnome.org/GNOME/gnome-tweaks/commit/c553730f

Documentation:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-provides

Specifically, I think this is used by the GNOME Software app to associate reviews posted for the old name to display them in the same place as reviews for the new name.

**Comment by zdohnal** [comment]
Hi Jeremy,

thank you for noticing it! I completely missed the paragraph about what causes renaming... I'll fix it right away.

**Comment by zdohnal** [comment]
Solved with https://github.com/zdohnal/system-config-printer/commit/e32648370ee9d68dc6c333fbac7252a62acffc33
